# Generated by Django 5.1.1 on 2024-09-21 02:24

import courses.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=courses.models.handle_upload)),
                ('access', models.CharField(choices=[('Anyone', 'Anyone'), ('Email_required', 'Email_required')], default='Draft', max_length=16)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Draft', max_length=10)),
            ],
        ),
    ]
